### ISSUE TITLE
Create Sql Server database with an elastic pool

### ISSUE THREAD

**Issue by bryancrosby** [DbUp/dbup-sqlserver#13]
Are there any plans to add support for creating a SQL Server Database with an elastic pool? Obviously the elastic pool must exist first, but thought that may be provided by the end-user. There's currently a few overloads in `SqlServerExtensions` for some different editions of Azure Sql, but I couldn't find any support for creating a database in an elastic pool.

The syntax is:

``
CREATE DATABASE somedatabase ( SERVICE_OBJECTIVE = ELASTIC_POOL (name = [poolname] ));
``

**Comment by droyad** [comment]
#16 should enable this
