### ISSUE TITLE
Use Microsoft.Data.SqlClient to allow Azure Active Directory connections

### ISSUE THREAD

**Issue by chriswill** [DbUp/dbup-sqlserver#15]
Referencing [this post](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/).

I want to use a SQL connection string like 
`Server=myserver.database.windows.net,1433;Database=mydatabase;UID=a;Authentication=Active Directory Interactive`

but the app fails with a **Keyword not supported: 'authentication'** exception.  This is because System.Data.SqlClient doesn't understand the new authentication schemes supported in Microsoft.Data.SqlClient that support Sql Azure.

Upgrading to Microsoft.Data.SqlClient is a relatively painless process and would resolve this issue.  Would you accept a PR for this?

Note: I applied the overloads to .SqlDatabase suggested in https://github.com/DbUp/dbup-sqlserver/issues/7 but this did not help.

**Comment by droyad** [comment]
Resolved by #17
