### ISSUE TITLE
Outdated dependency -- Microsoft.Azure.Services.AppAuthentication

### ISSUE THREAD

**Issue by gesownd** [DbUp/dbup-sqlserver#18]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Description

Microsoft.Azure.Services.AppAuthentication v1.6.2 is no longer maintained and should be replaced with Azure.Identity

### What is the impact?

Projects using DbUp with MSSQL cannot take advantage of current assemblies due to this dependency.

**Comment by droyad** [comment]
Duplicate of #12, Will be fixed by #14
