### ISSUE TITLE
Please add AAD auth support for Azure SQL Database

### ISSUE THREAD

**Issue by nzolotar** [DbUp/dbup-sqlserver#7]
I cant get it to work because you only accept connection as a string! And I need to get Azure token first and then establish a connection. Please advise if there any options. urgent project!
```
        private async Task<string> GetToken()
        {

            var ctx = new AuthenticationContext("https://login.microsoftonline.com/xxx");
            var result = await ctx.AcquireTokenAsync("https://database.windows.net/", new ClientCredential("xxx", "xxx"));
            return result.AccessToken;
        }
```
and then 
```
using (var conn = new SqlConnection("Data Source=tcp:xxx.database.windows.net,1433;Initial Catalog=xxx;"))
            {
                conn.AccessToken = await GetToken();

                return await conn.QueryASync<T>(sql);
            }
```

**Comment by mcolebiltd** [comment]
Base url for updated links:
https://github.com/DbUp/dbup-sqlserver/tree/main/src/dbup-sqlserver

**Comment by droyad** [comment]
@holtalanm in v5 there is an [overload that lets you set the resource or azureAdInstance](https://github.com/DbUp/dbup-sqlserver/blob/eab38c7acfdaf96a29babefd50c17d0bd156b940/src/dbup-sqlserver/AzureSqlConnectionManager.cs#L21) when using `https://github.com/DbUp/dbup-sqlserver/blob/eab38c7acfdaf96a29babefd50c17d0bd156b940/src/dbup-sqlserver/AzureSqlConnectionManager.cs#L21` (I think you want the latter)

In v6 (#14) you will be able to pass a `TokenCredential` which [lets you set your cloud](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#cloud-configuration)
